/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GerenciadorDeHoteis.Views;

import GerenciadorDeHoteis.Entity.Hospede;
import GerenciadorDeHoteis.Entity.ProdutoEServico;
import GerenciadorDeHoteis.Entity.Reserva;
import GerenciadorDeHoteis.Service.TipoService;
import GerenciadorDeHoteis.Entity.ReservaDespesa;
import GerenciadorDeHoteis.Repository.TipoRepository;
import GerenciadorDeHoteis.Utils.DatasUtil;
import GerenciadorDeHoteis.Utils.FormatoStringUtil;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Marcos
 */
public class GerenciamentoConta extends javax.swing.JFrame {

    private int idSelecionado = -1;
    private TipoService tipoService = new TipoService();

    /**
     * Creates new form GerenciamentoDeQuarto
     */
    public GerenciamentoConta() {
        initComponents();
        obtemDataConsumo();
        preencherAtualizarTabelaHospede();
        preencherAtualizarTabelaProduto();
        preencherComboBoxPesquisa();
        selecionarHospede();
        selecionarProduto();
        telaPesquisa.setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaPesquisa = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        txtValorPesquisa = new javax.swing.JTextField();
        cmbPesquisa = new javax.swing.JComboBox<>();
        bntPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblCampoPesquisa1 = new javax.swing.JLabel();
        lblValorPesquisa1 = new javax.swing.JLabel();
        lbPesquisa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblDataHoje = new javax.swing.JLabel();
        bntLimparCampos = new javax.swing.JButton();
        lblProdutoSelecionado = new javax.swing.JLabel();
        lblTabelaProdutos = new javax.swing.JLabel();
        lblTabelaHospedes = new javax.swing.JLabel();
        btnRefreshProduto = new javax.swing.JButton();
        btnRefreshHospede = new javax.swing.JButton();
        scpHospedes = new javax.swing.JScrollPane();
        tbHospedes = new javax.swing.JTable();
        scpProdutos = new javax.swing.JScrollPane();
        tbProduto = new javax.swing.JTable();
        lblPesquisarProduto = new javax.swing.JLabel();
        lblGerenciamentoDeContas = new javax.swing.JLabel();
        lblHospedeSelecionado = new javax.swing.JLabel();
        lblHospedePassaporte = new javax.swing.JLabel();
        lblHospedeCpf = new javax.swing.JLabel();
        lblValorProduto = new javax.swing.JLabel();
        txtPesquisarProduto = new javax.swing.JTextField();
        lblQuantidadeProduto = new javax.swing.JLabel();
        bntPesquisarProduto = new javax.swing.JButton();
        lblHospede = new javax.swing.JLabel();
        btnAdicionarHospede = new javax.swing.JButton();
        lblPassaporte = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblProduto = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        txtQuantidadeProduto = new javax.swing.JTextField();
        bntPesquisaHospede = new javax.swing.JButton();
        btnAdicionarproduto = new javax.swing.JButton();
        bntRealizarCheckIn = new javax.swing.JButton();
        bntDesselecionarHospede = new javax.swing.JButton();
        bntDesselecionarProduto = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTitleProduto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTitleProduto1 = new javax.swing.JLabel();
        lblTitleProduto2 = new javax.swing.JLabel();

        telaPesquisa.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtValorPesquisa.setBackground(new java.awt.Color(153, 153, 153));
        txtValorPesquisa.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jPanel2.add(txtValorPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 270, 30));

        cmbPesquisa.setBackground(new java.awt.Color(153, 153, 153));
        cmbPesquisa.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jPanel2.add(cmbPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 260, 30));

        bntPesquisar.setBackground(new java.awt.Color(153, 153, 153));
        bntPesquisar.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        bntPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Pesquisar.png"))); // NOI18N
        bntPesquisar.setText("Pesquisar");
        bntPesquisar.setToolTipText("Pesquisar Hospede");
        bntPesquisar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bntPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(bntPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 120, 40));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pesquisar Hospede");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 420, -1));

        lblCampoPesquisa1.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        lblCampoPesquisa1.setText("Campo a Pesquisar :");
        jPanel2.add(lblCampoPesquisa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        lblValorPesquisa1.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        lblValorPesquisa1.setText("Valor da Pesquisar :");
        jPanel2.add(lblValorPesquisa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 110, 30));

        lbPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 0, 12))); // NOI18N
        jPanel2.add(lbPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 370, 250));

        telaPesquisa.getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GERENCIADOR DE CONTA");
        setPreferredSize(new java.awt.Dimension(1625, 1200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDataHoje.setBackground(new java.awt.Color(0, 0, 0));
        lblDataHoje.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        lblDataHoje.setText("data");
        jPanel1.add(lblDataHoje, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 50, 150, -1));

        bntLimparCampos.setBackground(new java.awt.Color(153, 153, 153));
        bntLimparCampos.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        bntLimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_LimparTela.png"))); // NOI18N
        bntLimparCampos.setText("Limpar Campos");
        bntLimparCampos.setToolTipText("Limpar Campos");
        bntLimparCampos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntLimparCampos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bntLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLimparCamposActionPerformed(evt);
            }
        });
        jPanel1.add(bntLimparCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 660, 120, 50));

        lblProdutoSelecionado.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblProdutoSelecionado.setText("Produto Selecionado :");
        jPanel1.add(lblProdutoSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, 180, 20));

        lblTabelaProdutos.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lblTabelaProdutos.setText("PRODUTOS");
        jPanel1.add(lblTabelaProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 140, 30));

        lblTabelaHospedes.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lblTabelaHospedes.setText("HOSPEDES");
        jPanel1.add(lblTabelaHospedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 140, 30));

        btnRefreshProduto.setBackground(new java.awt.Color(153, 153, 153));
        btnRefreshProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Atualizar.png"))); // NOI18N
        btnRefreshProduto.setToolTipText("Atualiza a tabela de produtos");
        btnRefreshProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefreshProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRefreshProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefreshProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 60, 40));

        btnRefreshHospede.setBackground(new java.awt.Color(153, 153, 153));
        btnRefreshHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Atualizar.png"))); // NOI18N
        btnRefreshHospede.setToolTipText("Atualizar a Tabela Hospede");
        btnRefreshHospede.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefreshHospede.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRefreshHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshHospedeActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefreshHospede, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 60, 40));

        tbHospedes.setBackground(new java.awt.Color(153, 153, 153));
        tbHospedes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbHospedes.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        tbHospedes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome Hospede", "CPF", "Passaporte"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpHospedes.setViewportView(tbHospedes);
        if (tbHospedes.getColumnModel().getColumnCount() > 0) {
            tbHospedes.getColumnModel().getColumn(1).setResizable(false);
            tbHospedes.getColumnModel().getColumn(2).setResizable(false);
            tbHospedes.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(scpHospedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 410, 720));

        tbProduto.setBackground(new java.awt.Color(153, 153, 153));
        tbProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbProduto.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        tbProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Produto/Serviço", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scpProdutos.setViewportView(tbProduto);

        jPanel1.add(scpProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 410, 720));

        lblPesquisarProduto.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblPesquisarProduto.setText("Pesquisar Produto :");
        jPanel1.add(lblPesquisarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 760, 180, -1));

        lblGerenciamentoDeContas.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        lblGerenciamentoDeContas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGerenciamentoDeContas.setText("Gerenciamento de Contas");
        jPanel1.add(lblGerenciamentoDeContas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 1470, -1));

        lblHospedeSelecionado.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblHospedeSelecionado.setText("Hospede Selecionado :");
        jPanel1.add(lblHospedeSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 220, 200, 20));

        lblHospedePassaporte.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblHospedePassaporte.setText("Hospede Passaporte :");
        jPanel1.add(lblHospedePassaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 190, 20));

        lblHospedeCpf.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblHospedeCpf.setText("Hospede CPF :");
        jPanel1.add(lblHospedeCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, -1, 20));

        lblValorProduto.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblValorProduto.setText("Produto Valor :");
        jPanel1.add(lblValorProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 550, -1, 20));

        txtPesquisarProduto.setBackground(new java.awt.Color(153, 153, 153));
        txtPesquisarProduto.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        txtPesquisarProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarProdutoActionPerformed(evt);
            }
        });
        txtPesquisarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarProdutoKeyPressed(evt);
            }
        });
        jPanel1.add(txtPesquisarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 790, 230, 30));

        lblQuantidadeProduto.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        lblQuantidadeProduto.setText("Quantidade Produto :");
        jPanel1.add(lblQuantidadeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 600, -1, 20));

        bntPesquisarProduto.setBackground(new java.awt.Color(153, 153, 153));
        bntPesquisarProduto.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        bntPesquisarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Pesquisar.png"))); // NOI18N
        bntPesquisarProduto.setText("Pesquisar ");
        bntPesquisarProduto.setToolTipText("Pesquisar Produto");
        bntPesquisarProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntPesquisarProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bntPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPesquisarProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(bntPesquisarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 460, 120, 50));

        lblHospede.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHospede.setToolTipText("");
        jPanel1.add(lblHospede, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 220, 210, 20));

        btnAdicionarHospede.setBackground(new java.awt.Color(153, 153, 153));
        btnAdicionarHospede.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        btnAdicionarHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/botao-adicionar.png"))); // NOI18N
        btnAdicionarHospede.setText("Adicionar");
        btnAdicionarHospede.setToolTipText("Adicionar Hospede");
        btnAdicionarHospede.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdicionarHospede.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAdicionarHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarHospedeActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionarHospede, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 330, 120, 50));

        lblPassaporte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblPassaporte.setToolTipText("");
        jPanel1.add(lblPassaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 340, 200, 20));

        lblCPF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCPF.setToolTipText("");
        jPanel1.add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 280, 250, 20));

        lblProduto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblProduto.setToolTipText("");
        jPanel1.add(lblProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 500, 210, 20));

        lblValor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblValor.setToolTipText("");
        jPanel1.add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 550, 270, 20));

        txtQuantidadeProduto.setBackground(new java.awt.Color(153, 153, 153));
        txtQuantidadeProduto.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        txtQuantidadeProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQuantidadeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(txtQuantidadeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 600, 90, 30));

        bntPesquisaHospede.setBackground(new java.awt.Color(153, 153, 153));
        bntPesquisaHospede.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        bntPesquisaHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Pesquisar.png"))); // NOI18N
        bntPesquisaHospede.setText("Pesquisar");
        bntPesquisaHospede.setToolTipText("Pesquisar Hospede");
        bntPesquisaHospede.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntPesquisaHospede.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bntPesquisaHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPesquisaHospedeActionPerformed(evt);
            }
        });
        jPanel1.add(bntPesquisaHospede, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 210, 120, 50));

        btnAdicionarproduto.setBackground(new java.awt.Color(153, 153, 153));
        btnAdicionarproduto.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        btnAdicionarproduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/botao-adicionar.png"))); // NOI18N
        btnAdicionarproduto.setText("Adicionar");
        btnAdicionarproduto.setToolTipText("Adicionar Produto");
        btnAdicionarproduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdicionarproduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAdicionarproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarprodutoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionarproduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 580, 120, 50));

        bntRealizarCheckIn.setBackground(new java.awt.Color(153, 153, 153));
        bntRealizarCheckIn.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        bntRealizarCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Salvar.png"))); // NOI18N
        bntRealizarCheckIn.setText("Registrar");
        bntRealizarCheckIn.setToolTipText("Registrar Consumo do Hospede");
        bntRealizarCheckIn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntRealizarCheckIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bntRealizarCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRealizarCheckInActionPerformed(evt);
            }
        });
        jPanel1.add(bntRealizarCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 690, 150, 50));

        bntDesselecionarHospede.setBackground(new java.awt.Color(153, 153, 153));
        bntDesselecionarHospede.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        bntDesselecionarHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Desmarcar.png"))); // NOI18N
        bntDesselecionarHospede.setText("Desselecionar ");
        bntDesselecionarHospede.setToolTipText("Desselecionar Hospede");
        bntDesselecionarHospede.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntDesselecionarHospede.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bntDesselecionarHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDesselecionarHospedeActionPerformed(evt);
            }
        });
        jPanel1.add(bntDesselecionarHospede, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 270, 120, 50));

        bntDesselecionarProduto.setBackground(new java.awt.Color(153, 153, 153));
        bntDesselecionarProduto.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        bntDesselecionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Desmarcar.png"))); // NOI18N
        bntDesselecionarProduto.setText("Desselecionar ");
        bntDesselecionarProduto.setToolTipText("Desselecionar Produto");
        bntDesselecionarProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntDesselecionarProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bntDesselecionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDesselecionarProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(bntDesselecionarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 520, 120, 50));

        btnSair.setBackground(new java.awt.Color(153, 153, 153));
        btnSair.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Sair_1.png"))); // NOI18N
        btnSair.setToolTipText("Sair da tela de gerenciamento de conta");
        btnSair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 0, 60, 40));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 40));

        lblTitleProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hospede", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 0, 18))); // NOI18N
        jPanel1.add(lblTitleProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 180, 140, 210));

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hospede", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 0, 18))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 430, 210));

        lblTitleProduto1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 0, 18))); // NOI18N
        jPanel1.add(lblTitleProduto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 450, 410, 210));

        lblTitleProduto2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 0, 18))); // NOI18N
        jPanel1.add(lblTitleProduto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 420, 140, 240));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1550, 1030));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPesquisarActionPerformed
        // TODO add your handling code here:
        pesquisarHospede();
    }//GEN-LAST:event_bntPesquisarActionPerformed

    private void bntPesquisaHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPesquisaHospedeActionPerformed
        // TODO add your handling code here:
        telaPesquisa.setVisible(true);
    }//GEN-LAST:event_bntPesquisaHospedeActionPerformed

    private void bntDesselecionarHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDesselecionarHospedeActionPerformed
        // TODO add your handling code here:
        desselecionarHospede();
    }//GEN-LAST:event_bntDesselecionarHospedeActionPerformed

    private void bntLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLimparCamposActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_bntLimparCamposActionPerformed

    private void bntRealizarCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRealizarCheckInActionPerformed
        // TODO add your handling code here:
        criarDespesa();
    }//GEN-LAST:event_bntRealizarCheckInActionPerformed

    private void bntDesselecionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDesselecionarProdutoActionPerformed
        // TODO add your handling code here:
        desselecionarProduto();
    }//GEN-LAST:event_bntDesselecionarProdutoActionPerformed

    private void bntPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPesquisarProdutoActionPerformed
        // TODO add your handling code here:
        pesquisarProduto();
    }//GEN-LAST:event_bntPesquisarProdutoActionPerformed

    private void txtPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarProdutoActionPerformed

    private void txtQuantidadeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeProdutoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnRefreshHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshHospedeActionPerformed
        // TODO add your handling code here:
        preencherAtualizarTabelaHospede();
    }//GEN-LAST:event_btnRefreshHospedeActionPerformed

    private void btnRefreshProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshProdutoActionPerformed
        // TODO add your handling code here:
        preencherAtualizarTabelaProduto();
    }//GEN-LAST:event_btnRefreshProdutoActionPerformed

    private void txtPesquisarProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarProdutoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarProdutoKeyPressed

    private void btnAdicionarHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarHospedeActionPerformed
    }//GEN-LAST:event_btnAdicionarHospedeActionPerformed

    private void btnAdicionarprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarprodutoActionPerformed
    GerenciamentoDeProdutosEServico gerenciamentoDeProdutosEServico = new GerenciamentoDeProdutosEServico();
    gerenciamentoDeProdutosEServico.setVisible(true);
    }//GEN-LAST:event_btnAdicionarprodutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoConta().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntDesselecionarHospede;
    private javax.swing.JButton bntDesselecionarProduto;
    private javax.swing.JButton bntLimparCampos;
    private javax.swing.JButton bntPesquisaHospede;
    private javax.swing.JButton bntPesquisar;
    private javax.swing.JButton bntPesquisarProduto;
    private javax.swing.JButton bntRealizarCheckIn;
    private javax.swing.JButton btnAdicionarHospede;
    private javax.swing.JButton btnAdicionarproduto;
    private javax.swing.JButton btnRefreshHospede;
    private javax.swing.JButton btnRefreshProduto;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cmbPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbPesquisa;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCampoPesquisa1;
    private javax.swing.JLabel lblDataHoje;
    private javax.swing.JLabel lblGerenciamentoDeContas;
    private javax.swing.JLabel lblHospede;
    private javax.swing.JLabel lblHospedeCpf;
    private javax.swing.JLabel lblHospedePassaporte;
    private javax.swing.JLabel lblHospedeSelecionado;
    private javax.swing.JLabel lblPassaporte;
    private javax.swing.JLabel lblPesquisarProduto;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblProdutoSelecionado;
    private javax.swing.JLabel lblQuantidadeProduto;
    private javax.swing.JLabel lblTabelaHospedes;
    private javax.swing.JLabel lblTabelaProdutos;
    private javax.swing.JLabel lblTitleProduto;
    private javax.swing.JLabel lblTitleProduto1;
    private javax.swing.JLabel lblTitleProduto2;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorPesquisa1;
    private javax.swing.JLabel lblValorProduto;
    private javax.swing.JScrollPane scpHospedes;
    private javax.swing.JScrollPane scpProdutos;
    private javax.swing.JTable tbHospedes;
    private javax.swing.JTable tbProduto;
    private javax.swing.JFrame telaPesquisa;
    private javax.swing.JTextField txtPesquisarProduto;
    private javax.swing.JTextField txtQuantidadeProduto;
    private javax.swing.JTextField txtValorPesquisa;
    // End of variables declaration//GEN-END:variables

    private void criarReservaDespesa() {
        TipoRepository tipoRepository = new TipoRepository();
        DatasUtil datasUtil = new DatasUtil();
        double valorProdutoNumero;
        int quantidadeProdutoNumero;
        int idReserva = tipoService.buscarIdReserva(lblCPF.getText(), lblPassaporte.getText());
        String nome = lblHospede.getText();
        String produto = lblProduto.getText();
        String valorProduto = lblValor.getText();
        String quantidadeProduto = txtQuantidadeProduto.getText();
        Date dataConsumo = datasUtil.converterStringParaDataHoras(lblDataHoje.getText());
        double total = tipoService.ultimoTotal(idReserva);
        
        Reserva reserva = tipoRepository.buscarReservaPorId(idReserva);
        ProdutoEServico produtoEServico = tipoRepository.buscarPorNomeProduto(produto);
        
        try {
            quantidadeProdutoNumero = Integer.parseInt(quantidadeProduto);
            valorProdutoNumero = Double.parseDouble(valorProduto);

        } catch (NumberFormatException e) {
            JOptionPane.showInternalMessageDialog(null, "O campo VALOR DIARIA e/ou CAMPO DE QUANTIDADE DE PRODUTO deve conter um número válido.");
            System.out.println("O campo VALOR DIARIA e/ou CAMPO DE QUANTIDADE DE PRODUTO deve ser um número válido." + e.getMessage());
            return;
        }
        double valorSoma = valorProdutoNumero * quantidadeProdutoNumero;
        double totalSoma = total + valorSoma;
        
        ReservaDespesa reservaDespesa = new ReservaDespesa(reserva, produtoEServico, nome, produto, dataConsumo, quantidadeProdutoNumero, valorSoma, totalSoma);
        alterarStoque(quantidadeProdutoNumero, produto);
        tipoService.salvarReservaDespesa(reservaDespesa, reserva, false);
    }
     
    private void criarDespesa() {
        criarReservaDespesa();
    }

    private void alterarStoque(int quantidadeProduto, String produto) {
        int quantidadeEmStoque = tipoService.buscarQuantidadeProduto(produto);
        int produtoNome = tipoService.buscarIdProduto(produto);

        if (quantidadeEmStoque - quantidadeProduto < 0) {
            JOptionPane.showInternalMessageDialog(null, "Sem produto o sufuciente em estoque.");
            return;

        } else {
            System.out.println("A quantidade em estoque foi alterada com sucesso.");
            tipoService.atualizarQuantidadeEstoque(produtoNome, quantidadeEmStoque - quantidadeProduto);
        }
    }

    private void preencherAtualizarTabelaHospede() {
        tipoService.preencherTabelaHospede(tbHospedes);
    }

    private void preencherAtualizarTabelaProduto() {
        tipoService.preencherTabelaProdutoConta(tbProduto);
    }

    private void pesquisarHospede() {
        FormatoStringUtil formatoStringUtil = new FormatoStringUtil();
        String campo = (String) cmbPesquisa.getSelectedItem();
        String valor = txtValorPesquisa.getText();
        if (campo.equals("Id") || campo.equals("CPF")) {
            try {
                int id = Integer.parseInt(valor);
                int cpf = Integer.parseInt(formatoStringUtil.pegaNumeroDaString(valor));

            } catch (NumberFormatException e) {
                if (campo.equals("Id")) {
                    JOptionPane.showMessageDialog(null, "O campo de pesquisa ID possui um caractere invalido.");

                } else if (campo.equals("CPF")) {
                    JOptionPane.showMessageDialog(null, "O campo de pesquisa CPF possui um caractere invalido.");

                }
                System.out.println("O campo Id não aceita Letra e o Campo Numero de camas não aceita numero maior que 128" + e.getMessage());
                return;
            }
        }
        tipoService.pesquisaHospede(campo, valor, tbHospedes);
    }

    private void pesquisarProduto() {
        String valor = txtValorPesquisa.getText();
        tipoService.pesquisaProduto("nome", valor, tbProduto);
    }

    private void selecionarHospede() {
        tbHospedes.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int index = tbHospedes.getSelectedRow();
                    if (index != -1) {
                        idSelecionado = (int) tbHospedes.getValueAt(index, 0);
                        Hospede hospede = tipoService.retornaIdHospede(getIdSelecionado());
                        lblHospede.setText(hospede.getNome());
                        lblCPF.setText(hospede.getCpf());
                        lblPassaporte.setText(hospede.getPassaporte());
                    }
                }
            }
        });
    }

    private void selecionarProduto() {
        tbProduto.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    int index = tbProduto.getSelectedRow();
                    if (index != -1) {
                        idSelecionado = (int) tbProduto.getValueAt(index, 0);
                        ProdutoEServico produto = tipoService.retornaIdProdutoEServico(getIdSelecionado());
                        lblProduto.setText(produto.getNome());
                        lblValor.setText(String.valueOf(produto.getValor()));
                        txtQuantidadeProduto.setText("1");
                    }
                }
            }
        });
    }

    private void desselecionarHospede() {
        lblHospede.setText("");
        lblCPF.setText("");
        lblPassaporte.setText("");
        idSelecionado = -1;
    }

    private void desselecionarProduto() {
        lblProduto.setText("");
        lblValor.setText("");
        txtQuantidadeProduto.setText("");
        idSelecionado = -1;
    }

    private void limparCampos() {
        txtPesquisarProduto.setText("");
        txtQuantidadeProduto.setText("");
    }

    private JComboBox<String> getComboBoxColunas(JComboBox<String> comboBox) {
        comboBox.removeAllItems();

        for (int i = 0; i < getTbHospedes().getColumnCount(); i++) {
            String nomeColuna = getTbHospedes().getColumnName(i);
            comboBox.addItem(nomeColuna);
        }
        return comboBox;
    }

    private void preencherComboBoxPesquisa() {
        cmbPesquisa = getComboBoxColunas(cmbPesquisa);
    }

    private JTable getTbHospedes() {
        return tbHospedes;
    }

    private int getIdSelecionado() {
        return idSelecionado;
    }

    private void obtemDataConsumo() {
        DatasUtil datasUtil = new DatasUtil();
        datasUtil.converterDataParaString(datasUtil.obtemDataHoje(lblDataHoje), "dd/MM/yyyy");
    }
}