/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GerenciadorDeHoteis.Views;

import GerenciadorDeHoteis.Entity.Hospede;
import GerenciadorDeHoteis.Service.TipoService;
import GerenciadorDeHoteis.Utils.DatasUtil;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcos
 */
public class CadastrarHospede extends javax.swing.JFrame {

    private TipoService tipoService = new TipoService();
    private static String cpfFuncionario;
    private static String cpfHospede;
    private static String passaporteHospede;
    private int idSelecionado = -1;

    /**
     * Creates new form CadastroHospede
     */
    public CadastrarHospede(String cpfFuncionario) {
        //verificarCpf(cpfFuncionario);
        this.cpfFuncionario = cpfFuncionario;
        initComponents();
        preencherPaises();
        this.setLocationRelativeTo(null);
        preencherAtualizarTabela();
        selecionarHospede();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTelefone = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPassaporte = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        cmbPais = new javax.swing.JComboBox<>();
        lblTxtPrecoDiaria = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        bntSalvar = new javax.swing.JButton();
        bntCheckIn = new javax.swing.JToggleButton();
        lblNome = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        lblHospede = new javax.swing.JLabel();
        lblNome2 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblPassaporte = new javax.swing.JLabel();
        btnLimparCampos = new javax.swing.JButton();
        btnDesselecionar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblMargensBotoes = new javax.swing.JLabel();
        lblDadosGerais = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHospedes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CADASTRO DE HOSPEDE");
        setMinimumSize(new java.awt.Dimension(950, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTelefone.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        lblTelefone.setText("Telefone :");
        jPanel1.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 80, -1));

        lblCpf.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        lblCpf.setText("CPF :");
        jPanel1.add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 40, -1));

        lblEmail.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        lblEmail.setText("Email :");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 50, -1));

        lblPais.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        lblPais.setText("Pais :");
        jPanel1.add(lblPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 50, -1));

        lblDataNascimento.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        lblDataNascimento.setText("Data Nascimento :");
        jPanel1.add(lblDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        txtNome.setBackground(new java.awt.Color(153, 153, 153));
        txtNome.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        txtNome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 220, 30));

        txtEmail.setBackground(new java.awt.Color(153, 153, 153));
        txtEmail.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        txtEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 220, 30));

        txtPassaporte.setBackground(new java.awt.Color(153, 153, 153));
        txtPassaporte.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        txtPassaporte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtPassaporte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPassaporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassaporteActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 220, 30));

        txtCpf.setBackground(new java.awt.Color(153, 153, 153));
        txtCpf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCpf.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jPanel1.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 220, 30));

        txtTelefone.setBackground(new java.awt.Color(153, 153, 153));
        txtTelefone.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtTelefone.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        jPanel1.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 220, 30));

        cmbPais.setBackground(new java.awt.Color(153, 153, 153));
        cmbPais.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        cmbPais.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbPais.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(cmbPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 220, 30));

        lblTxtPrecoDiaria.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(lblTxtPrecoDiaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 420, 210, 30));

        txtDataNascimento.setBackground(new java.awt.Color(153, 153, 153));
        txtDataNascimento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascimento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtDataNascimento.setFont(new java.awt.Font("Segoe UI Variable", 0, 12)); // NOI18N
        txtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascimentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 230, 30));

        bntSalvar.setBackground(new java.awt.Color(153, 153, 153));
        bntSalvar.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        bntSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Salvar_1.png"))); // NOI18N
        bntSalvar.setText("Salvar ");
        bntSalvar.setToolTipText("");
        bntSalvar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bntSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(bntSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 110, 40));

        bntCheckIn.setBackground(new java.awt.Color(153, 153, 153));
        bntCheckIn.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        bntCheckIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/check-in.png"))); // NOI18N
        bntCheckIn.setText("Check In");
        bntCheckIn.setToolTipText("ir Para Check -in");
        bntCheckIn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bntCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCheckInActionPerformed(evt);
            }
        });
        jPanel1.add(bntCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 110, 40));

        lblNome.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("Cadastro de Hospede");
        lblNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 40));

        lblNome1.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        lblNome1.setText("Hospede:");
        jPanel1.add(lblNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 70, -1));

        lblHospede.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(lblHospede, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 200, 30));

        lblNome2.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        lblNome2.setText("Nome :");
        jPanel1.add(lblNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 50, -1));

        btnPesquisar.setBackground(new java.awt.Color(153, 153, 153));
        btnPesquisar.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Pesquisar.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 110, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/aperto-de-mao.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 130, 120));

        lblPassaporte.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        lblPassaporte.setText("Passaporte :");
        jPanel1.add(lblPassaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 90, -1));

        btnLimparCampos.setBackground(new java.awt.Color(153, 153, 153));
        btnLimparCampos.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        btnLimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_LimparTela.png"))); // NOI18N
        btnLimparCampos.setText("Limpar");
        btnLimparCampos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimparCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 110, 40));

        btnDesselecionar.setBackground(new java.awt.Color(153, 153, 153));
        btnDesselecionar.setFont(new java.awt.Font("Arial Narrow", 0, 10)); // NOI18N
        btnDesselecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Desmarcar.png"))); // NOI18N
        btnDesselecionar.setText("Desselecionar");
        btnDesselecionar.setToolTipText("Limpar Campo");
        btnDesselecionar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDesselecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesselecionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDesselecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 110, 40));

        btnSair.setBackground(new java.awt.Color(153, 153, 153));
        btnSair.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Sair_1.png"))); // NOI18N
        btnSair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 60, 40));

        lblMargensBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(lblMargensBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 130, 270));

        lblDadosGerais.setBackground(new java.awt.Color(204, 204, 204));
        lblDadosGerais.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Gerais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 0, 14))); // NOI18N
        jPanel1.add(lblDadosGerais, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 710, 370));

        tbHospedes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Cpf", "Passaporte"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbHospedes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 960, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoActionPerformed

    private void bntSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarActionPerformed
        // TODO add your handling code here:
        criarHospede();
    }//GEN-LAST:event_bntSalvarActionPerformed

    private void bntCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCheckInActionPerformed
        // TODO add your handling code here:
        abrirTelaCheckInCheckOut();
    }//GEN-LAST:event_bntCheckInActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        // TODO add your handling code here:
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtPassaporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassaporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassaporteActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnDesselecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesselecionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDesselecionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarHospede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarHospede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarHospede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarHospede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarHospede(cpfFuncionario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bntCheckIn;
    private javax.swing.JButton bntSalvar;
    private javax.swing.JButton btnDesselecionar;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cmbPais;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDadosGerais;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHospede;
    private javax.swing.JLabel lblMargensBotoes;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblNome2;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPassaporte;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTxtPrecoDiaria;
    private javax.swing.JTable tbHospedes;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPassaporte;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
    private void criarHospede() {
        DatasUtil datasUtil = new DatasUtil();
        String nome = txtNome.getText();
        String cpf = txtCpf.getText();
        String passaporte = txtPassaporte.getText().toUpperCase();
        String email = txtEmail.getText();
        String telefone = txtTelefone.getText();
        String pais = (String) cmbPais.getSelectedItem();
        Date dataNascimento = datasUtil.converterStringParaData(txtDataNascimento.getText());
        Hospede hospede = new Hospede(nome, cpf, passaporte, email, telefone, pais, dataNascimento);
        tipoService.salvarHospede(hospede);
        setCpfHospede(cpf);
        setPassaporteHospede(passaporte);
        limparCampos();
    }

    private void abrirTelaCheckInCheckOut() {
        String cpf = getCpfHospede();
        String passaporte = getPassaporteHospede();
        if (cpf != null && passaporte != null) {
            GerenciamentoCheckInCheckOut checkInCheckOut = new GerenciamentoCheckInCheckOut(getCpfFuncionario(), cpf, passaporte);
            checkInCheckOut.setVisible(true);

        } else if (cpf != null && passaporte == null) {
            GerenciamentoCheckInCheckOut checkInCheckOut = new GerenciamentoCheckInCheckOut(getCpfFuncionario(), cpf, null);
            checkInCheckOut.setVisible(true);

        } else if (passaporte != null && cpf == null) {
            GerenciamentoCheckInCheckOut checkInCheckOut = new GerenciamentoCheckInCheckOut(getCpfFuncionario(), null, passaporte);
            checkInCheckOut.setVisible(true);

        } else {
            GerenciamentoCheckInCheckOut checkInCheckOut = new GerenciamentoCheckInCheckOut(getCpfFuncionario(), null, null);
            checkInCheckOut.setVisible(true);

        }
        this.dispose();
    }

    private void preencherPaises() {
        tipoService.preencherComboBoxPaises(cmbPais);
    }

    private void limparCampos() {
        txtNome.setText("");
        txtCpf.setText("");
        txtPassaporte.setText("");
        txtEmail.setText("");
        txtTelefone.setText("");
        cmbPais.setSelectedItem(1);
        txtDataNascimento.setText("");
    }

    private void selecionarHospede() {
        tbHospedes.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                DatasUtil datasUtil = new DatasUtil();
                if (e.getClickCount() == 2) {
                    int index = tbHospedes.getSelectedRow();
                    if (index != -1) {
                        idSelecionado = (int) tbHospedes.getValueAt(index, 0);
                        Hospede hospede = tipoService.retornaIdHospede(getIdSelecionado());
                        lblHospede.setText(hospede.getNome());
                        txtNome.setText(hospede.getNome());
                        txtCpf.setText(hospede.getCpf());
                        txtTelefone.setText(hospede.getTelefone());
                        txtEmail.setText(hospede.getEmail());
                        cmbPais.setSelectedItem(hospede.getPais());
                        txtPassaporte.setText(hospede.getPassaporte());
                        txtDataNascimento.setText(datasUtil.converterDataParaString(hospede.getDataNascimento(), "dd/MM/yyyy"));

                    }
                }
            }
        });
    }

    public static String getCpfFuncionario() {
        return cpfFuncionario;
    }

    private int getIdSelecionado() {
        return idSelecionado;
    }

    public static void setCpfFuncionario(String cpfFuncionario) {
        CadastrarHospede.cpfFuncionario = cpfFuncionario;
    }

    public static String getCpfHospede() {
        return cpfHospede;
    }

    public static void setCpfHospede(String cpfHospede) {
        CadastrarHospede.cpfHospede = cpfHospede;
    }

    public static String getPassaporteHospede() {
        return passaporteHospede;
    }

    private void preencherAtualizarTabela() {
        tipoService.preencherTabelaHospedeCheckIn(tbHospedes);
    }

    public static void setPassaporteHospede(String passaporteHospede) {
        CadastrarHospede.passaporteHospede = passaporteHospede;
    }

    public void verificarCpf(String cpfFuncionario) {
        if (cpfFuncionario == null) {
            JOptionPane.showInternalMessageDialog(null, "Erro o Cpf de funcionario esta nulo. Tente relogar.");
            throw new IllegalArgumentException("CPF esta nulo");
        }
    }
}