/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GerenciadorDeHoteis.Views;

import GerenciadorDeHoteis.Service.TipoService;
import GerenciadorDeHoteis.Types.Quarto;
import GerenciadorDeHoteis.Repository.TipoRepository;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos
 */
public class GerenciamentoDeQuarto extends javax.swing.JFrame {

    TipoService tipoService = new TipoService();
    TipoRepository tipoRepository = new TipoRepository();
    //private int quartoId = 0;

    /**
     * Creates new form GerenciamentoDeQuarto
     */
    public GerenciamentoDeQuarto() {
        initComponents();
        preencherAtualizarTabela();
        telaPesquisa.setSize(445, 450);
        telaEditar.setSize(250, 380);
        cbmCampoPesquisa = getComboBoxColunas(cbmCampoPesquisa);
        telaPesquisa.setLocationRelativeTo(null);
        telaEditar.setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaPesquisa = new javax.swing.JFrame();
        lblPesquisa = new javax.swing.JLabel();
        lblCampoPesquisa = new javax.swing.JLabel();
        lblValorPesquisa = new javax.swing.JLabel();
        cbmCampoPesquisa = new javax.swing.JComboBox<>();
        txtCampoPesquisa = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        btnFecharPesquisar = new javax.swing.JToggleButton();
        lblFundoPesquisa = new javax.swing.JLabel();
        telaEditar = new javax.swing.JFrame();
        lblEdicaoQuarto = new javax.swing.JLabel();
        lblIdEditar = new javax.swing.JLabel();
        lblNomeQuartoEdicao = new javax.swing.JLabel();
        lblTipoQuartoEdicao = new javax.swing.JLabel();
        lblNumeroCamasEdicao = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtNomeQuartoEdicao = new javax.swing.JTextField();
        cmbTipoQuartoEdicao = new javax.swing.JComboBox<>();
        txtNumeroCamasEdicao = new javax.swing.JTextField();
        btnQuartoEdicao = new javax.swing.JButton();
        btnFecharEdicao = new javax.swing.JButton();
        cbxQuartoOcupadoEdicao = new javax.swing.JCheckBox();
        lblTelaEditar = new javax.swing.JLabel();
        lblGerenciamentoDeQuatos = new javax.swing.JLabel();
        lblNomeQuarto = new javax.swing.JLabel();
        lblTipoQuarto = new javax.swing.JLabel();
        lblNumeroCamas = new javax.swing.JLabel();
        txtNomeQuarto = new javax.swing.JTextField();
        cmbTipoQuarto = new javax.swing.JComboBox<>();
        txtNumeroCamas = new javax.swing.JTextField();
        cbxQuartoOcupado = new javax.swing.JCheckBox();
        btnRegistarQuarto = new javax.swing.JButton();
        btnPesquisarQuarto = new javax.swing.JToggleButton();
        btnEditarQuarto = new javax.swing.JToggleButton();
        btnDeletar = new javax.swing.JToggleButton();
        btnRefersh = new javax.swing.JToggleButton();
        btnSair = new javax.swing.JToggleButton();
        scpQuartos = new javax.swing.JScrollPane();
        tbQuartos = new javax.swing.JTable();
        lblFundo = new javax.swing.JLabel();

        telaPesquisa.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPesquisa.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblPesquisa.setText("Campo De Pesquisa");
        telaPesquisa.getContentPane().add(lblPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 30));

        lblCampoPesquisa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCampoPesquisa.setText("Campo a Pesquisar :");
        telaPesquisa.getContentPane().add(lblCampoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lblValorPesquisa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblValorPesquisa.setText("Valor da Pesquisar :");
        telaPesquisa.getContentPane().add(lblValorPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, 30));

        telaPesquisa.getContentPane().add(cbmCampoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 180, 40));

        txtCampoPesquisa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtCampoPesquisa.setToolTipText("valor do campo que quer pesquisar");
        telaPesquisa.getContentPane().add(txtCampoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 370, 40));

        btnPesquisa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.setToolTipText("efetua a pesquisa");
        btnPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });
        telaPesquisa.getContentPane().add(btnPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 130, 30));

        btnFecharPesquisar.setText("Fechar");
        btnFecharPesquisar.setToolTipText("fecha essa tela");
        btnFecharPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        telaPesquisa.getContentPane().add(btnFecharPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 130, 30));

        lblFundoPesquisa.setText("Fundo Pesquisa");
        telaPesquisa.getContentPane().add(lblFundoPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 680, 410));

        telaEditar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEdicaoQuarto.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblEdicaoQuarto.setText("Editção de Quartos");
        telaEditar.getContentPane().add(lblEdicaoQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 40));

        lblIdEditar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblIdEditar.setText("ID :");
        telaEditar.getContentPane().add(lblIdEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 30));

        lblNomeQuartoEdicao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNomeQuartoEdicao.setText("Nome do Quarto :");
        telaEditar.getContentPane().add(lblNomeQuartoEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 30));

        lblTipoQuartoEdicao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTipoQuartoEdicao.setText("Tipo de Quarto :");
        telaEditar.getContentPane().add(lblTipoQuartoEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 150, 30));

        lblNumeroCamasEdicao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNumeroCamasEdicao.setText("Nº de Camas :");
        telaEditar.getContentPane().add(lblNumeroCamasEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 30));

        lblId.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        lblId.setText("Id");
        telaEditar.getContentPane().add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 30, 50));

        txtNomeQuartoEdicao.setToolTipText("numero do quarto");
        telaEditar.getContentPane().add(txtNomeQuartoEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, 30));

        cmbTipoQuartoEdicao.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cmbTipoQuartoEdicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Solteiro Duplo", "Quarto Casal", "Apartamento", "Suite" }));
        telaEditar.getContentPane().add(cmbTipoQuartoEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 150, 30));

        txtNumeroCamasEdicao.setToolTipText("numero de camas no quarto");
        telaEditar.getContentPane().add(txtNumeroCamasEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 210, 30));

        btnQuartoEdicao.setText("Editar Quarto");
        btnQuartoEdicao.setToolTipText("efetua o registro de um quarto");
        btnQuartoEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuartoEdicaoActionPerformed(evt);
            }
        });
        telaEditar.getContentPane().add(btnQuartoEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        btnFecharEdicao.setText("Fechar");
        btnFecharEdicao.setToolTipText("efetua o registro de um quarto");
        btnFecharEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharEdicaoActionPerformed(evt);
            }
        });
        telaEditar.getContentPane().add(btnFecharEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        cbxQuartoOcupadoEdicao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cbxQuartoOcupadoEdicao.setText("Quarto Ocupado");
        cbxQuartoOcupadoEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxQuartoOcupadoEdicaoActionPerformed(evt);
            }
        });
        telaEditar.getContentPane().add(cbxQuartoOcupadoEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 170, 40));

        lblTelaEditar.setText("Fundo Editar");
        telaEditar.getContentPane().add(lblTelaEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 350));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGerenciamentoDeQuatos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblGerenciamentoDeQuatos.setText("Gerenciamento de Quartos");
        getContentPane().add(lblGerenciamentoDeQuatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 320, 40));

        lblNomeQuarto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNomeQuarto.setText("Nome do Quarto :");
        getContentPane().add(lblNomeQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 160, 30));

        lblTipoQuarto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTipoQuarto.setText("Tipo de Quarto :");
        getContentPane().add(lblTipoQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 150, 30));

        lblNumeroCamas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNumeroCamas.setText("Nº de Camas :");
        getContentPane().add(lblNumeroCamas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 130, 30));

        txtNomeQuarto.setToolTipText("numero do quarto");
        getContentPane().add(txtNomeQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 270, 30));

        cmbTipoQuarto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cmbTipoQuarto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Solteiro Duplo", "Quarto Casal", "Apartamento", "Suite" }));
        getContentPane().add(cmbTipoQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 150, 30));

        txtNumeroCamas.setToolTipText("numero de camas no quarto");
        getContentPane().add(txtNumeroCamas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 270, 30));

        cbxQuartoOcupado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cbxQuartoOcupado.setText("Quarto Ocupado");
        getContentPane().add(cbxQuartoOcupado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 170, 40));

        btnRegistarQuarto.setText("Registrar Quarto");
        btnRegistarQuarto.setToolTipText("efetua o registro de um quarto");
        btnRegistarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistarQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 160, 40));

        btnPesquisarQuarto.setText("Pesquisar Quarto");
        btnPesquisarQuarto.setToolTipText("abre a tela de pesquisa");
        btnPesquisarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisarQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 120, -1));

        btnEditarQuarto.setText("Editar Quarto");
        btnEditarQuarto.setToolTipText("seleciona um quarto para editar");
        btnEditarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditarQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 120, -1));

        btnDeletar.setText("Excluir Quarto");
        btnDeletar.setToolTipText("efetua a edição");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 120, -1));

        btnRefersh.setText("Recarregar/Julinha Mude S2");
        btnRefersh.setToolTipText("recarrega a tabela");
        btnRefersh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefershActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefersh, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 330, 170, -1));

        btnSair.setText("Sair/Julinha Mude S2");
        btnSair.setToolTipText("fecha essa tela");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 170, -1));

        tbQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome Quarto", "Tipo Do Quarto", "Nº De Camas", "Status Ocupação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scpQuartos.setViewportView(tbQuartos);
        if (tbQuartos.getColumnModel().getColumnCount() > 0) {
            tbQuartos.getColumnModel().getColumn(0).setResizable(false);
            tbQuartos.getColumnModel().getColumn(1).setResizable(false);
            tbQuartos.getColumnModel().getColumn(2).setResizable(false);
            tbQuartos.getColumnModel().getColumn(3).setResizable(false);
            tbQuartos.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(scpQuartos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 990, 210));

        lblFundo.setText("Fundo");
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarQuartoActionPerformed
        // TODO add your handling code here:
        criarQuarto();
        preencherAtualizarTabela();
    }//GEN-LAST:event_btnRegistarQuartoActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        deletar();
        preencherAtualizarTabela();
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnEditarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarQuartoActionPerformed
        // TODO add your handling code here:
        editar();
    }//GEN-LAST:event_btnEditarQuartoActionPerformed

    private void btnPesquisarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarQuartoActionPerformed
        // TODO add your handling code here:
        telaPesquisa.setVisible(true);
    }//GEN-LAST:event_btnPesquisarQuartoActionPerformed

    private void btnRefershActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefershActionPerformed
        // TODO add your handling code here:
        preencherAtualizarTabela();
    }//GEN-LAST:event_btnRefershActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        // TODO add your handling code here:       
        pesquisar();
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnSairActionPerformed

    private void cbxQuartoOcupadoEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxQuartoOcupadoEdicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxQuartoOcupadoEdicaoActionPerformed

    private void btnFecharEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharEdicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFecharEdicaoActionPerformed

    private void btnQuartoEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuartoEdicaoActionPerformed
        // TODO add your handling code here:
        atualizarQuarto();
        preencherAtualizarTabela();
    }//GEN-LAST:event_btnQuartoEdicaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoDeQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoDeQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoDeQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoDeQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoDeQuarto().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDeletar;
    private javax.swing.JToggleButton btnEditarQuarto;
    private javax.swing.JButton btnFecharEdicao;
    private javax.swing.JToggleButton btnFecharPesquisar;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JToggleButton btnPesquisarQuarto;
    private javax.swing.JButton btnQuartoEdicao;
    private javax.swing.JToggleButton btnRefersh;
    private javax.swing.JButton btnRegistarQuarto;
    private javax.swing.JToggleButton btnSair;
    private javax.swing.JComboBox<String> cbmCampoPesquisa;
    private javax.swing.JCheckBox cbxQuartoOcupado;
    private javax.swing.JCheckBox cbxQuartoOcupadoEdicao;
    private javax.swing.JComboBox<String> cmbTipoQuarto;
    private javax.swing.JComboBox<String> cmbTipoQuartoEdicao;
    private javax.swing.JLabel lblCampoPesquisa;
    private javax.swing.JLabel lblEdicaoQuarto;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblFundoPesquisa;
    private javax.swing.JLabel lblGerenciamentoDeQuatos;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdEditar;
    private javax.swing.JLabel lblNomeQuarto;
    private javax.swing.JLabel lblNomeQuartoEdicao;
    private javax.swing.JLabel lblNumeroCamas;
    private javax.swing.JLabel lblNumeroCamasEdicao;
    private javax.swing.JLabel lblPesquisa;
    private javax.swing.JLabel lblTelaEditar;
    private javax.swing.JLabel lblTipoQuarto;
    private javax.swing.JLabel lblTipoQuartoEdicao;
    private javax.swing.JLabel lblValorPesquisa;
    private javax.swing.JScrollPane scpQuartos;
    private javax.swing.JTable tbQuartos;
    private javax.swing.JFrame telaEditar;
    private javax.swing.JFrame telaPesquisa;
    private javax.swing.JTextField txtCampoPesquisa;
    private javax.swing.JTextField txtNomeQuarto;
    private javax.swing.JTextField txtNomeQuartoEdicao;
    private javax.swing.JTextField txtNumeroCamas;
    private javax.swing.JTextField txtNumeroCamasEdicao;
    // End of variables declaration//GEN-END:variables

    private void criarQuarto() {
        byte numeroCamasNumero;
        String nome = txtNomeQuarto.getText().trim();
        String tipoQuarto = (String) cmbTipoQuarto.getSelectedItem();
        String numeroCamas = txtNumeroCamas.getText().trim();
        boolean quartoOcupado = cbxQuartoOcupado.isSelected();

        try {
            numeroCamasNumero = Byte.parseByte(numeroCamas);
        } catch (NumberFormatException e) {
            JOptionPane.showInternalMessageDialog(null, "O campo cama deve ser um número válido.");
            return;
        }
        Quarto quarto = new Quarto(nome, tipoQuarto, numeroCamasNumero, quartoOcupado);
        tipoService.salvarQuarto(quarto);
    }

    private void preencherAtualizarTabela() {
        DefaultTableModel tabela = (DefaultTableModel) tbQuartos.getModel();
        tabela.setRowCount(0);
        List<Object[]> objeto = tipoService.preencherTabelaQuarto();
        if (objeto == null) {
            JOptionPane.showInternalMessageDialog(null, "O valor pesquisado não foi encrontrado.");
        } else {
            for (Object[] linha : objeto) {
                tabela.addRow(linha);
            }
        }
    }

    private int selecionarQuarto() {
        int index = tbQuartos.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um quarto na Tabela antes de editar ou excluir", "Erro", JOptionPane.ERROR_MESSAGE);
            return -1;
        } else {
            int id = (int) tbQuartos.getValueAt(index, 0);
            return id;
        }
    }

    private void atualizarQuarto() {
        String nome = txtNomeQuartoEdicao.getText();
        String tipoQuarto = (String) cmbTipoQuartoEdicao.getSelectedItem();
        byte numeroCamas = Byte.parseByte(txtNumeroCamasEdicao.getText());
        boolean quartoOcupado = cbxQuartoOcupadoEdicao.isSelected();
        Quarto quarto = new Quarto(nome, tipoQuarto, numeroCamas, quartoOcupado);
        System.out.println("quarto id " + selecionarQuarto());
        tipoService.atulizarQuartoService(selecionarQuarto(), quarto);
    }

    private void deletar() {
        if (validaEdicao()) {
            tipoService.deletarQuartoService(selecionarQuarto());
        }
    }

    private void pesquisar() {
        DefaultTableModel tabela = (DefaultTableModel) tbQuartos.getModel();
        tabela.setRowCount(0);
        String campo = (String) cbmCampoPesquisa.getSelectedItem();
        String valor = txtCampoPesquisa.getText();
        List<Object[]> objeto = tipoService.pesquisaQuarto(campo, valor);
        if (objeto == null) {
            JOptionPane.showInternalMessageDialog(null, "O valor pesquisado não foi encrontrado.");
        } else {
            for (Object[] linha : objeto) {
                tabela.addRow(linha);
            }
        }
    }

    private void editar() {
        if (validaEdicao()) {
            Quarto quarto = tipoRepository.buscarPorIdQuarto(selecionarQuarto());
            if (quarto != null) {
                lblId.setText(String.valueOf(quarto.getId()));
                txtNomeQuartoEdicao.setText(quarto.getNome());
                cmbTipoQuartoEdicao.setSelectedItem(quarto.getTipoQuarto());
                txtNumeroCamasEdicao.setText(String.valueOf(quarto.getNumeroCamas()));
                cbxQuartoOcupadoEdicao.setSelected(quarto.isStatus());
                telaEditar.setVisible(true);
            } else {
                System.out.println("O quarto selecionado não foi encontrado");
            }
        }
    }

    private boolean validaEdicao() {
        if (selecionarQuarto() < 0) {
            return false;
        }
        return true;
    }

    public JComboBox<String> getComboBoxColunas(JComboBox<String> comboBox) {
        comboBox.removeAllItems();

        for (int i = 0; i < getTbQuatos().getColumnCount(); i++) {
            String nomeColuna = getTbQuatos().getColumnName(i);
            comboBox.addItem(nomeColuna);
        }
        return comboBox;
    }

    public JTable getTbQuatos() {
        return tbQuartos;
    }
}
