/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GerenciadorDeHoteis.Views;

import GerenciadorDeHoteis.Entity.Funcionario;
import GerenciadorDeHoteis.Service.TipoService;

/**
 *
 * @author julia
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private static String cpfFuncionario;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(String cpfFuncionario) {
        this.cpfFuncionario= cpfFuncionario;
        initComponents();
        pegarNomeFuncionario(cpfFuncionario);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBemVindo = new javax.swing.JLabel();
        lblFuncionario = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();
        mBarMenu = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        btnCadastrarCliente = new javax.swing.JMenu();
        menuQuarto = new javax.swing.JMenu();
        btnGerenciarQuarto = new javax.swing.JMenu();
        menuProduto = new javax.swing.JMenu();
        btnGerenciarProduto = new javax.swing.JMenu();
        MenuReserva = new javax.swing.JMenu();
        btnCheckInCheckOut = new javax.swing.JMenu();
        MenuRelatorio = new javax.swing.JMenu();
        btnReserva = new javax.swing.JMenu();
        MenuFuncionario = new javax.swing.JMenu();
        btnCadastrarFuncionario = new javax.swing.JMenu();
        MenuSair = new javax.swing.JMenu();
        btnLogout = new javax.swing.JMenu();
        btnSair = new javax.swing.JMenu();

        setTitle("MENU PRINCIPAL");
        setMaximumSize(new java.awt.Dimension(2000, 1500));
        setMinimumSize(new java.awt.Dimension(2000, 1500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBemVindo.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        lblBemVindo.setText("SEJA BEM-VINDO:");
        getContentPane().add(lblBemVindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, -1));

        lblFuncionario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFuncionario.setText("Funcionario");
        getContentPane().add(lblFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 230, 30));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagem_FundoMenuPrincipal (1).png"))); // NOI18N
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -80, 2000, 1200));

        mBarMenu.setBackground(new java.awt.Color(204, 204, 204));
        mBarMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mBarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mBarMenu.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N

        menuCliente.setBackground(new java.awt.Color(102, 102, 102));
        menuCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Cliente64.png"))); // NOI18N
        menuCliente.setText("CLIENTE");

        btnCadastrarCliente.setBackground(new java.awt.Color(204, 204, 204));
        btnCadastrarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrarCliente.setText("Cadastrar Cliente");
        btnCadastrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCadastrarCliente.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        btnCadastrarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarClienteMouseClicked(evt);
            }
        });
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });
        menuCliente.add(btnCadastrarCliente);

        mBarMenu.add(menuCliente);

        menuQuarto.setBackground(new java.awt.Color(102, 102, 102));
        menuQuarto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_QuartoMenu64.png"))); // NOI18N
        menuQuarto.setText("QUARTO");
        menuQuarto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuartoMouseClicked(evt);
            }
        });

        btnGerenciarQuarto.setText("Gerenciar Quarto");
        btnGerenciarQuarto.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        btnGerenciarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarQuartoActionPerformed(evt);
            }
        });
        menuQuarto.add(btnGerenciarQuarto);

        mBarMenu.add(menuQuarto);

        menuProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Produto64.png"))); // NOI18N
        menuProduto.setText("PRODUTOS");
        menuProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProdutoMouseClicked(evt);
            }
        });

        btnGerenciarProduto.setText("Gerenciar Produtos");
        btnGerenciarProduto.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        menuProduto.add(btnGerenciarProduto);

        mBarMenu.add(menuProduto);

        MenuReserva.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MenuReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Reservado64.png"))); // NOI18N
        MenuReserva.setText("RESERVAS");

        btnCheckInCheckOut.setText("Check In e Check Out");
        btnCheckInCheckOut.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        btnCheckInCheckOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCheckInCheckOutMouseClicked(evt);
            }
        });
        MenuReserva.add(btnCheckInCheckOut);

        mBarMenu.add(MenuReserva);

        MenuRelatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MenuRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Relátorio64.png"))); // NOI18N
        MenuRelatorio.setText("RELÁTORIOS");

        btnReserva.setText("Reservas");
        btnReserva.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        btnReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReservaMouseClicked(evt);
            }
        });
        MenuRelatorio.add(btnReserva);

        mBarMenu.add(MenuRelatorio);

        MenuFuncionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MenuFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/Icone_Funcionario.png"))); // NOI18N
        MenuFuncionario.setText("FUNCIONÁRIO");

        btnCadastrarFuncionario.setText("Cadastrar Funcionário");
        btnCadastrarFuncionario.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        btnCadastrarFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarFuncionarioMouseClicked(evt);
            }
        });
        MenuFuncionario.add(btnCadastrarFuncionario);

        mBarMenu.add(MenuFuncionario);

        MenuSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icone/exit.png"))); // NOI18N
        MenuSair.setText("SAIR");
        MenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSairMouseClicked(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        MenuSair.add(btnLogout);

        btnSair.setText("Sair");
        btnSair.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSairMouseClicked(evt);
            }
        });
        MenuSair.add(btnSair);

        mBarMenu.add(MenuSair);

        setJMenuBar(mBarMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnGerenciarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGerenciarQuartoActionPerformed

    private void btnCadastrarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarClienteMouseClicked
        // TODO add your handling code here:
        CadastrarHospede cadastrarHospede = new CadastrarHospede(cpfFuncionario);
        cadastrarHospede.setVisible(true);
    }//GEN-LAST:event_btnCadastrarClienteMouseClicked

    private void menuQuartoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuartoMouseClicked
        // TODO add your handling code here:
        GerenciamentoDeQuarto gerenciamentoDeQuarto = new GerenciamentoDeQuarto();
        gerenciamentoDeQuarto.setVisible(true);
    }//GEN-LAST:event_menuQuartoMouseClicked

    private void menuProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProdutoMouseClicked
        // TODO add your handling code here:
        GerenciamentoDeProdutosEServico gerenciamentoDeProdutosEServico = new GerenciamentoDeProdutosEServico();
        gerenciamentoDeProdutosEServico.setVisible(true);
    }//GEN-LAST:event_menuProdutoMouseClicked

    private void btnCheckInCheckOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckInCheckOutMouseClicked
        // TODO add your handling code here:
        GerenciamentoCheckInCheckOut checkInCheckOut = new GerenciamentoCheckInCheckOut(getCpfFuncionario(), null, null);
        checkInCheckOut.setVisible(true);
    }//GEN-LAST:event_btnCheckInCheckOutMouseClicked

    private void btnReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservaMouseClicked

    private void btnCadastrarFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarFuncionarioMouseClicked
        // TODO add your handling code here:
        CadastroFuncionarios cadastroFuncionarios = new CadastroFuncionarios();
        cadastroFuncionarios.setVisible(true);
    }//GEN-LAST:event_btnCadastrarFuncionarioMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        LoginFuncionario loginFuncionario = new LoginFuncionario();
        loginFuncionario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairMouseClicked

    private void MenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new MenuPrincipal(cpfFuncionario).setVisible(true);
                    }
                });
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuFuncionario;
    private javax.swing.JMenu MenuRelatorio;
    private javax.swing.JMenu MenuReserva;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenu btnCadastrarCliente;
    private javax.swing.JMenu btnCadastrarFuncionario;
    private javax.swing.JMenu btnCheckInCheckOut;
    private javax.swing.JMenu btnGerenciarProduto;
    private javax.swing.JMenu btnGerenciarQuarto;
    private javax.swing.JMenu btnLogout;
    private javax.swing.JMenu btnReserva;
    private javax.swing.JMenu btnSair;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JMenuBar mBarMenu;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuProduto;
    private javax.swing.JMenu menuQuarto;
    // End of variables declaration//GEN-END:variables
    private void pegarNomeFuncionario(String cpf) {
        if (cpf == null) {
            lblFuncionario.setText("");
        } else {
            TipoService tipoService = new TipoService();
            Funcionario funcionario = tipoService.buscarFuncionarioPorId(getCpfFuncionario());
            lblFuncionario.setText(funcionario.getNome());
        }
    }

    public static String getCpfFuncionario() {
        return cpfFuncionario;
    }

    public static void setCpfFuncionario(String cpfFuncionario) {
        MenuPrincipal.cpfFuncionario = cpfFuncionario;
    }
}