/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GerenciadorDeHoteis.Views;

import GerenciadorDeHoteis.Service.TipoService;

/**
 *
 * @author Marcos
 */
public class Reserva extends javax.swing.JFrame {
    TipoService tipoService = new TipoService();

    /**
     * Creates new form CadastroHospede
     */
    public Reserva() {
        initComponents();
        preencherComboBoxPaises();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblPassaporte = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblDataCheckIn = new javax.swing.JLabel();
        lblTipoQuarto = new javax.swing.JLabel();
        lblNumeroQuarto = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtPassaporte = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        cmbPais = new javax.swing.JComboBox<>();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        lblTxtDataCheckIn = new javax.swing.JLabel();
        cmbTipoQuarto = new javax.swing.JComboBox<>();
        cmbNumeroQuarto = new javax.swing.JComboBox<>();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNome.setText("Nome :");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 70, -1));

        lblCpf.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCpf.setText("CPF :");
        getContentPane().add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 50, -1));

        lblPassaporte.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPassaporte.setText("Passaporte :");
        getContentPane().add(lblPassaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 110, -1));

        lblEmail.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblEmail.setText("Email :");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 70, -1));

        lblTelefone.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTelefone.setText("Telefone :");
        getContentPane().add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 90, -1));

        lblPais.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblPais.setText("Pais :");
        getContentPane().add(lblPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 50, -1));

        lblDataNascimento.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDataNascimento.setText("Data Nascimento :");
        getContentPane().add(lblDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 160, -1));

        lblDataCheckIn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDataCheckIn.setText("Data Check In:");
        getContentPane().add(lblDataCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 130, -1));

        lblTipoQuarto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTipoQuarto.setText("Tipo de Quarto :");
        getContentPane().add(lblTipoQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 90, 160, -1));

        lblNumeroQuarto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNumeroQuarto.setText("Nº Quarto :");
        getContentPane().add(lblNumeroQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 190, 100, -1));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 330, 30));

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 330, 30));
        getContentPane().add(txtPassaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 330, 30));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 330, 30));
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 330, 30));

        getContentPane().add(cmbPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 150, -1));

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 330, 30));

        lblTxtDataCheckIn.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblTxtDataCheckIn.setText("Data");
        getContentPane().add(lblTxtDataCheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 210, -1));

        getContentPane().add(cmbTipoQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 120, 150, -1));

        getContentPane().add(cmbNumeroQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 220, 150, -1));

        lblFundo.setText("Fundo");
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbNumeroQuarto;
    private javax.swing.JComboBox<String> cmbPais;
    private javax.swing.JComboBox<String> cmbTipoQuarto;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDataCheckIn;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumeroQuarto;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPassaporte;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipoQuarto;
    private javax.swing.JLabel lblTxtDataCheckIn;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPassaporte;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
   private void criarHospede(){
       String nome = txtNome.getText();
       String cpf = txtCpf.getText();
   }
    
    private void preencherComboBoxPaises(){
        String[] paises = tipoService.listaPaises();
        for (String pais : paises) {
            cmbPais.addItem(pais);
        }
    }
    
}
